version: "3.8"

services:
  web:
    container_name: attendance_tracker_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    container_name: attendance_tracker_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - web

  db:
    container_name: postgres_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  db:
    driver: bridge
